name: workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install flask pandas joblib pybuilder sklearn
      - run: cd pybuilder && pyb -v
#       - run: python3 script.py
 
